import {
  FaGraduationCap,
  FaUniversity,
  FaSchool,
  FaBriefcase,
  FaBookOpen,
  FaCertificate,
  FaMicrochip,
  FaDraftingCompass,
  FaCubes,
  FaServer,
  FaGlobeEurope,
  FaNetworkWired,
  FaCloud,
  FaDatabase,
  FaHdd,
  FaCogs,
  FaShieldAlt,
  FaLanguage,
  FaGlobe,
  FaCalculator,
  FaFlask,
  FaAtom,
  FaBrain,
  FaGithub,
  FaHtml5,
  FaCss3,
  FaJava,
  FaReact,
  FaTools,
  FaGitAlt,
  FaJsSquare,
  FaNodeJs,
} from "react-icons/fa";

import {
  SiReact,
  SiJavascript,
  SiAutodesk,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiNextdotjs,
  SiNodedotjs,
  SiMongodb,
  SiTypescript,
  SiTailwindcss,
  SiExpress,
  SiArduino,
  SiCplusplus,
  SiServerfault,
  SiLibreofficemath,
  SiWolframmathematica,
  SiAutocad,
} from "react-icons/si";
import { RiEnglishInput } from "react-icons/ri";
import { MdElectricBolt, MdDomain } from "react-icons/md";
import { FcElectronics } from "react-icons/fc";

export const iconMap = {
  FaGraduationCap,
  MdDomain,
  RiEnglishInput,
  FaUniversity,
  FaSchool,
  SiAutodesk,
  FaBriefcase,
  FaBookOpen,
  FcElectronics,
  SiAutocad,
  FaCertificate,
  FaMicrochip,
  FaDraftingCompass,
  FaCubes,
  FaServer,
  FaGlobeEurope,
  FaNetworkWired,
  FaCloud,
  FaDatabase,
  FaHdd,
  FaCogs,
  FaShieldAlt,
  FaLanguage,
  FaGlobe,
  FaCalculator,
  FaFlask,
  FaAtom,
  FaBrain,
  FaGithub,
  FaHtml5,
  FaCss3,
  FaJava,
  FaReact,
  SiReact,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiNextdotjs,
  SiNodedotjs,
  SiMongodb,
  SiTypescript,
  SiTailwindcss,
  SiExpress,
  SiArduino,
  SiCplusplus,
  SiServerfault,
  SiLibreofficemath,
  SiWolframmathematica,
  MdElectricBolt,
  FaTools,
  FaGitAlt,
  FaJsSquare,
  FaNodeJs,
};

export const categoryColorMap = {
  education: "nm-inset text-[var(--bg-accent)] font-bold",
  internship: "nm-inset text-[var(--bg-accent)] font-bold",
  certificates: "nm-inset text-[var(--bg-accent)] font-bold",
};

export const iconColorMap = {
  FaHtml5: "text-orange-600",
  SiHtml5: "text-orange-600",
  FaCss3: "text-blue-500",
  SiCss3: "text-blue-500",
  FaJsSquare: "text-yellow-400",
  SiJavascript: "text-yellow-400",
  SiTypescript: "text-blue-600",
  FaReact: "text-cyan-400",
  SiReact: "text-cyan-400",
  SiNextdotjs: "text-black",
  FaNodeJs: "text-green-600",
  SiNodedotjs: "text-green-600",
  SiBootstrap: "text-purple-600",
  SiTailwindcss: "text-cyan-500",
  SiExpress: "text-gray-500",
  SiMongodb: "text-green-500",
  FaDatabase: "text-gray-600",
  FaGithub: "text-gray-500",
  FaGitAlt: "text-orange-600",
  FaCloud: "text-blue-400",
  FaServer: "text-gray-900",
  FaTools: "text-gray-600",
  SiArduino: "text-teal-500",
  SiCplusplus: "text-blue-600",
  FaJava: "text-red-600",
  SiAutocad: "text-red-600",
  SiAutodesk: "text-blue-600",
  SiServerfault: "text-orange-500",
  FcElectronics: "text-blue-500",
  MdElectricBolt: "text-yellow-500",
  FaMicrochip: "text-purple-500",
  FaGlobe: "text-cyan-500",
  FaLanguage: "text-indigo-500",
  RiEnglishInput: "text-blue-600",
  SiLibreofficemath: "text-green-600",
  SiWolframmathematica: "text-red-500",
  FaNetworkWired: "text-indigo-500",
  MdDomain: "text-purple-500",
};

export const getStatusBg = (status) => {
  switch (status) {
    case "completed":
      return "bg-blue-900 border-accent";
    case "current":
      return "bg-red-900 border-accent";
    case "upcoming":
      return "bg-yellow-500/20 border-accent";
    default:
      return "bg-gray-500/20 border-accent";
  }
};

